# Generated by Django 3.1.3 on 2020-11-13 17:31

import authlib.oauth2.rfc6749.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import oauth2_server.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuth2Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, default=oauth2_server.models.generate_client_id, max_length=32, unique=True)),
                ('client_secret', models.CharField(default=oauth2_server.models.generate_client_secret, max_length=48)),
                ('client_name', models.CharField(max_length=120)),
                ('scope', models.TextField()),
                ('response_type', models.CharField(choices=[('code', 'code'), ('token', 'token')], default='code', max_length=100)),
                ('grand_type', models.CharField(choices=[('authorization_code', 'authorization_code'), ('implicit', 'implicit'), ('password', 'password'), ('client_credentials', 'client_credentials')], default='authorization_code', max_length=100)),
                ('token_endpoint_auth_method', models.CharField(default='', max_length=120)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, authlib.oauth2.rfc6749.models.ClientMixin),
        ),
        migrations.CreateModel(
            name='OAuth2Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=255, unique=True)),
                ('refresh_token', models.CharField(blank=True, max_length=255, null=True)),
                ('scope', models.TextField()),
                ('issued_at', models.IntegerField(default=oauth2_server.models.now_timestamp)),
                ('expires_in', models.IntegerField(default=3600)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', related_query_name='token', to='oauth2_server.oauth2client')),
            ],
            bases=(models.Model, authlib.oauth2.rfc6749.models.TokenMixin),
        ),
        migrations.CreateModel(
            name='OAuth2ClientRedirectURI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redirect_uri', models.CharField(max_length=512)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redirect_uris', related_query_name='redirect_uri', to='oauth2_server.oauth2client')),
            ],
        ),
    ]
